# Generated by Django 4.2.6 on 2023-10-22 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_welcome_notifications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Welcome_Notifications',
            new_name='Welcome_Notification',
        ),
    ]
