# Generated by Django 4.2.6 on 2023-10-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_rename_welcome_notifications_welcome_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
