# Generated by Django 4.2.6 on 2023-10-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_general_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='general_notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
