# Generated by Django 4.2.6 on 2024-03-30 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('first_time_login', models.BooleanField(default=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('bio', models.TextField(default='i am a good kid')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
