# Generated by Django 4.2.6 on 2023-10-20 11:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
