# Generated by Django 4.2.6 on 2023-10-29 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_alter_profile_profile_image'),
        ('chatRoom', '0003_alter_room_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='host_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile'),
        ),
    ]
