# Generated by Django 4.2.6 on 2023-11-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatRoom', '0005_rename_host_image_room_host_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='stream_token',
            field=models.CharField(default='home', max_length=800),
        ),
    ]
