# Generated by Django 4.2.6 on 2023-11-02 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatRoom', '0006_room_stream_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='stream_token',
            new_name='agora_token',
        ),
    ]
