# Generated by Django 4.2.6 on 2023-10-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_rename_cards_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
