# Generated by Django 4.2.6 on 2023-10-24 16:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_card_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_items',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.card')),
            ],
        ),
    ]
