# Generated by Django 4.2.6 on 2023-10-24 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_card_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card_items',
            new_name='Card_item',
        ),
    ]
